---
openapi: 3.0.1
info:
  title: Psychonnect API
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
paths:
  "/secret":
    get:
      summary: Endpoint protegido
      tags:
      - Auth
      security:
      - bearerAuth: []
      responses:
        '200':
          description: acesso permitido
        '401':
          description: acesso negado
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
