# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  port: 5432

# --- ENVIRONMENTS ------------------------------------------------------

development:
  <<: *default
  database: psychonnect_dev
  host: localhost
  username: psychonnect
  password: password

test:
  <<: *default
  database: psychonnect_test
  host: localhost
  username: psychonnect
  password: password

production:
  # Primary (writes/reads)
  primary: &primary_production
    <<: *default
    database: psychonnect_production

  # Solid Trifecta connections — point to the same DB for now
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
  cable:
    <<: *primary_production
