default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["PSYCHONNECT_DATABASE_USERNAME"] %>
  password: <%= ENV["PSYCHONNECT_DATABASE_PASSWORD"] %>
  host: localhost
  pool: 5

development:
  <<: *default
  database: psychonnect_dev

test:
  <<: *default
  database: psychonnect_dev

production:
  <<: *default
  database: psychonnect_production
  username: psychonnect
  password: <%= ENV["PSYCHONNECT_DATABASE_PASSWORD"] %>
