# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  port: 5432

# --- ENVIRONMENTS ------------------------------------------------------

development:
  <<: *default
  database: psychonnect_dev

test:
  <<: *default
  database: psychonnect_test

production:
  # Primary (writes/reads)
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DATABASE", "psychonnect_production") %>

  # Solid Trifecta connections — point to the same DB for now
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
  cable:
    <<: *primary_production
