default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  pool: 10

development:
  <<: *default
  database: psychonnect_dev

test:
  <<: *default
  database: psychonnect_test

production:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST") %>
  database: <%= ENV.fetch("POSTGRES_DATABASE") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  port: 5432