default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  pool: 10

development:
  <<: *default
  database: psychonnect_dev

test:
  <<: *default
  database: psychonnect_test

production:
  primary: &primary
    <<: *default
    host: <%= ENV.fetch("DATABASE_HOST") %>
    database: psychonnect_production
    username: <%= ENV.fetch("POSTGRES_USERNAME") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
    port: 5432

  cache:
    <<: *primary
    database: psychonnect_production_cache

  queue:
    <<: *primary

  cable:
    <<: *primary