service: psychonnect
image: gyodai/psychonnect

servers:
  web:
    - do-droplet-1

proxy:
  ssl: true
  host: 167.99.9.143

registry:
  # server: docker.io
  username: gyodai
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    DATABASE_HOST: psychonnect-postgres
    POSTGRES_USERNAME: psychonnect
    POSTGRES_USER: psychonnect
    POSTGRES_DB: psychonnect_production
    RAILS_ENV: production
    #SWAGGER_HOST: 167.99.9.143
    #SWAGGER_SCHEME: http
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    
accessories:
  psychonnect-postgres:
    image: postgres:15
    host: do-droplet-1
    port: 16
    directories:
      - data:/var/lib/postgresql/data
    env:
      clear:
        DATABASE_HOST: psychonnect-postgres
        POSTGRES_USERNAME: psychonnect
        POSTGRES_USERNAME: psychonnect
        POSTGRES_DB: psychonnect_production
      secret:
        - POSTGRES_PASSWORD