service: psychonnect
image: gyodai/psychonnect

servers:
  web:
    - do-droplet-1

registry:
  server: docker.io
  username: gyodai
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    DB_HOST: psychonnect-postgres
    POSTGRES_USER: psychonnect
    POSTGRES_DB: psychonnect_production
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    
accessories:
  postgres:
    image: postgres:15
    host: do-droplet-1
    directories:
      - data:/var/lib/postgresql/data
    env:
      clear:
        POSTGRES_USER: psychonnect
        POSTGRES_DB: psychonnect_production
      secret:
        - POSTGRES_PASSWORD