name: CI
on: [push, pull_request]

defaults:
  run:
    shell: bash

# Âncora pra não repetir checkout+Ruby
steps-common: &ruby_setup
  - uses: actions/checkout@v4
  - uses: ruby/setup-ruby@v1
    with:
      ruby-version: .ruby-version
      bundler-cache: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      *ruby_setup
      - run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      *ruby_setup
      - run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports: [5432:5432]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/psychonect_test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - name: OS deps
        run: sudo apt-get update && sudo apt-get install -y build-essential libpq-dev
      *ruby_setup
      - run: bin/rails db:prepare
      - run: bundle exec rspec
